#MAKEFILE
# name of compiler: wdjc
# name of file extension: .dj

# FILES NEEDED

# TESTS = \
# ....


 OBJS = ast.cmo parser.cmo scanner.cmo wdjc.cmo
#	semcheck.cmo compile.cmo 

wdjc : $(OBJS)
	ocamlc -o wdjc $(OBJS)


.PHONY : test
test : wdjc testall.sh
	./testall.sh


scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<s

.PHONY :	 clean
clean :
	rm -f wdjc parser.ml parser.mli scanner.ml testall.log \
	*.cmo *.cmi *.out *.diff

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx:
compile.cmo: ast.cmo 
compile.cmx: ast.cmx 
wdjc.cmo: scanner.cmo parser.cmi compile.cmo ast.cmo 
wdjc.cmx: scanner.cmx parser.cmx compile.cmx ast.cmx 
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmo 




